# Generated by Django 5.0.6 on 2026-06-23 17:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('dairy', 'Dairy'), ('snacks', 'Snacks'), ('hygiene', 'Hygiene'), ('everyday', 'Everyday Needs')], db_index=True, default='everyday', max_length=32)),
                ('price', models.DecimalField(decimal_places=2, help_text='Current selling price.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum retail price; used to show a discount badge.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('unit', models.CharField(blank=True, help_text="e.g. '500 ml', '1 kg', '100 g'.", max_length=50)),
                ('image_emoji', models.CharField(blank=True, help_text='Emoji used as a lightweight thumbnail.', max_length=8)),
                ('is_veg', models.BooleanField(default=True)),
                ('deal_badge', models.CharField(blank=True, help_text="Optional promotional label, e.g. 'Buy 1 Get 1'.", max_length=60, null=True)),
                ('estimated_delivery_time', models.PositiveIntegerField(default=15, help_text='Estimated delivery time in minutes.')),
                ('is_active', models.BooleanField(default=True, help_text='Soft on/off switch for marketplace visibility.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='products_pr_categor_226e74_idx')],
            },
        ),
    ]
